// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0jLTU-s9m_ElMSuBHs4vWwb4kLHNm8JQ',
    appId: '1:825833569082:web:2cf9ad12d2fda78f906e03',
    messagingSenderId: '825833569082',
    projectId: 'current-da355',
    authDomain: 'current-da355.firebaseapp.com',
    storageBucket: 'current-da355.appspot.com',
    measurementId: 'G-7LRLLWB3J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXqY_QMPWuLBZdpLtVb-XBOeRVoLKWRsU',
    appId: '1:825833569082:android:8475689dfd0c6941906e03',
    messagingSenderId: '825833569082',
    projectId: 'current-da355',
    storageBucket: 'current-da355.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApu6D8t1_4kp-s2NiyxYluR7XOAEGNk0o',
    appId: '1:825833569082:ios:c57b47a09058af01906e03',
    messagingSenderId: '825833569082',
    projectId: 'current-da355',
    storageBucket: 'current-da355.appspot.com',
    iosBundleId: 'com.jerrychen.currentV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApu6D8t1_4kp-s2NiyxYluR7XOAEGNk0o',
    appId: '1:825833569082:ios:037ef343346c6220906e03',
    messagingSenderId: '825833569082',
    projectId: 'current-da355',
    storageBucket: 'current-da355.appspot.com',
    iosBundleId: 'com.jerrychen.currentV1.RunnerTests',
  );
}
